name: Build EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Python環境のセットアップ（安定した3.11を使用）
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 必要なライブラリのインストール
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # 必要なライブラリをインストール（PyQt6を含む）
        pip install pymupdf==1.24.10 PyQt6 pyinstaller

    # PyInstallerでexe化の実行

    # --neme ""をフォルダ名に修正必要
    - name: Build with PyInstaller
      run: >
        pyinstaller 
        --onefile 
        --noconsole 
        --clean 
        --name "HandwrittenImageMiya-v1.0.0" 
        --add-data "readme.md;."
        --collect-all pymupdf 
        --hidden-import fitz 
        --hidden-import PyQt6 
        app.pyw

    # 完成したexeファイルをGitHub上にアップロード

    # naem: フォルダ名に修正必要
    # path: dist/ファイル名.exe → ファイル名修正必要
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: HandwrittenImageMiya-v1.0.0
        path: dist/HandwrittenImageMiya-v1.0.0.exe